<a href="https://colab.research.google.com/github/Nenad523/mastering-git/blob/main/00PyTorchFundamentalsVideo(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reshaping, stacking, squeezing and unsqueezing tensors
* **Reshaping** - reshapes an input tensor to a defined shape.
* **View** - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other (**vstack**) or side by side (**hstack**)
* **Squeeze** - remove all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(start = 1, end = 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

As we can see above, when reshaping, dimensions you pass as arg, have to allow to store exactly the amount of numbers the original tensor has.

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped = x.reshape(1, 3, 3)
x_reshaped, x_reshaped.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

### STACKING
* Stack  -> https://docs.pytorch.org/docs/stable/generated/torch.stack.html
* Hstack -> https://docs.pytorch.org/docs/stable/generated/torch.vstack.html
* Vstack -> https://docs.pytorch.org/docs/stable/generated/torch.hstack.html

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack((x, x, x, x), dim=-2)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

### Squeezing and unsqueezing
* Squeezing -> https://docs.pytorch.org/docs/stable/generated/torch.squeeze.html
* Unsqueezing -> https://docs.pytorch.org/docs/stable/generated/torch.unsqueeze.html

In [ ]:
x1 = torch.rand(2, 1, 2)
x1, x1.shape

(tensor([[[0.7836, 0.3512]],
 
         [[0.8985, 0.7132]]]),
 torch.Size([2, 1, 2]))

In [ ]:
x2 = x1.squeeze()
x2, x2.shape

(tensor([[0.7836, 0.3512],
         [0.8985, 0.7132]]),
 torch.Size([2, 2]))

In [ ]:
x3 = torch.rand(2, 2)
x3, x3.shape

(tensor([[0.1441, 0.4755],
         [0.9197, 0.5768]]),
 torch.Size([2, 2]))

In [ ]:
x3.unsqueeze(0), x3.unsqueeze(0).shape

(tensor([[[0.1441, 0.4755],
          [0.9197, 0.5768]]]),
 torch.Size([1, 2, 2]))

In [ ]:
x3.unsqueeze(1), x3.unsqueeze(1).shape

(tensor([[[0.1441, 0.4755]],
 
         [[0.9197, 0.5768]]]),
 torch.Size([2, 1, 2]))

In [ ]:
x3.unsqueeze(2), x3.unsqueeze(2).shape

(tensor([[[0.1441],
          [0.4755]],
 
         [[0.9197],
          [0.5768]]]),
 torch.Size([2, 2, 1]))

## torch.permute - rearanges the dimensions of a target tensor in a specific order
Link -> https://docs.pytorch.org/docs/stable/generated/torch.permute.html

In [ ]:
x_original = torch.rand(size = (224, 224, 3))
x_original, x_original.shape

(tensor([[[0.7674, 0.2296, 0.2538],
          [0.0475, 0.3681, 0.1827],
          [0.6833, 0.3070, 0.1848],
          ...,
          [0.4383, 0.5169, 0.3835],
          [0.6968, 0.1275, 0.4118],
          [0.6059, 0.7175, 0.8325]],
 
         [[0.8136, 0.8269, 0.1562],
          [0.1712, 0.4796, 0.9132],
          [0.8983, 0.0971, 0.7463],
          ...,
          [0.5452, 0.2704, 0.8905],
          [0.5356, 0.3927, 0.3244],
          [0.6460, 0.9605, 0.3800]],
 
         [[0.1576, 0.7944, 0.7929],
          [0.6130, 0.8909, 0.0351],
          [0.6740, 0.2513, 0.1051],
          ...,
          [0.8287, 0.6362, 0.9889],
          [0.6031, 0.0898, 0.8631],
          [0.3407, 0.4433, 0.9166]],
 
         ...,
 
         [[0.4683, 0.0155, 0.1968],
          [0.2478, 0.8351, 0.1415],
          [0.9371, 0.2809, 0.1139],
          ...,
          [0.2359, 0.5346, 0.2712],
          [0.8493, 0.0885, 0.7959],
          [0.8376, 0.1874, 0.9279]],
 
         [[0.6141, 0.9708, 0.5606],
          [0

In [ ]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (2, 0, 1))
x_permuted, x_permuted.shape

(tensor([[[0.7674, 0.0475, 0.6833,  ..., 0.4383, 0.6968, 0.6059],
          [0.8136, 0.1712, 0.8983,  ..., 0.5452, 0.5356, 0.6460],
          [0.1576, 0.6130, 0.6740,  ..., 0.8287, 0.6031, 0.3407],
          ...,
          [0.4683, 0.2478, 0.9371,  ..., 0.2359, 0.8493, 0.8376],
          [0.6141, 0.5499, 0.2304,  ..., 0.7706, 0.6299, 0.5345],
          [0.4978, 0.6954, 0.0108,  ..., 0.0607, 0.5789, 0.0154]],
 
         [[0.2296, 0.3681, 0.3070,  ..., 0.5169, 0.1275, 0.7175],
          [0.8269, 0.4796, 0.0971,  ..., 0.2704, 0.3927, 0.9605],
          [0.7944, 0.8909, 0.2513,  ..., 0.6362, 0.0898, 0.4433],
          ...,
          [0.0155, 0.8351, 0.2809,  ..., 0.5346, 0.0885, 0.1874],
          [0.9708, 0.5376, 0.2574,  ..., 0.2410, 0.0526, 0.4618],
          [0.8265, 0.0834, 0.9935,  ..., 0.3329, 0.3393, 0.7209]],
 
         [[0.2538, 0.1827, 0.1848,  ..., 0.3835, 0.4118, 0.8325],
          [0.1562, 0.9132, 0.7463,  ..., 0.8905, 0.3244, 0.3800],
          [0.7929, 0.0351, 0.1051,  ...,

## Indexing (selecting data form tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (dim = 2)
x[0][0][0]

tensor(1)

In [ ]:
# Let's get number 9
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension, but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension, but onyl the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values from 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0][2][2]

tensor(9)

In [ ]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to intercat with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflect numpy's default datatype of float64 unless specified otherwise

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
# Change the value of array, what will happen to `tensor`?
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

As we can see they do not share the same memory allocation, only datatype

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

Same goes with memory and dtype as above.

## Reproducibility (trying to take random out of random)

In short, how NN learns:
`starti with random numbers -> tensor operations -> update random number -> again..`

To reduce the randomness in NN and PyTorch comes the concept of a **random seed**.

Essentialy, what the random seed does is "flavour" the randomness.

Link -> https://docs.pytorch.org/docs/stable/notes/randomness.html

In [ ]:
torch.rand(3, 3)

tensor([[0.8940, 0.4774, 0.5255],
        [0.4994, 0.0097, 0.8235],
        [0.4446, 0.1082, 0.2324]])

In [ ]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1446, 0.2389, 0.0314, 0.5309],
        [0.6415, 0.3756, 0.5429, 0.9183],
        [0.9374, 0.2666, 0.0917, 0.1723]])
tensor([[0.5994, 0.5700, 0.6225, 0.2087],
        [0.7980, 0.4255, 0.1088, 0.4106],
        [0.5340, 0.5787, 0.4171, 0.3010]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible rensors
import torch

# Set the random seed
RANDOM_SEED = 42 # Different flavours to randomness
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tenors and PyTorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scens

from sre_constants import GROUPREF_UNI_IGNORE
### 1. Getting a GPU

1. Easiest - Use Google Colab for free GPU
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on a cloud and access ThreadedCompleter

In [1]:
!nvidia-smi

Wed Aug  6 16:16:45 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check fro GPU access with PyTorch

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count the number of GPU's
torch.cuda.device_count()

1