<a href="https://colab.research.google.com/github/Nenad523/mastering-git/blob/main/00PyTorchFundamentalsVideo(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

GitHub resource : https://github.com/mrdbourke/pytorch-deep-learning


## Introduction to Tensors  

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # Used to determine the rank of tensor (number of indexes used for vector component)

0

In [ ]:
scalar.item() # Get tensor back as Python int

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# Size of each dimension as a tuple
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

In [ ]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 1],
                        [2, 5, 4]]])

TENSOR


tensor([[[1, 2, 3],
         [3, 4, 1],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
 # PRACTICE

t1 = torch.tensor([[1, 2],
                   [1, 2, 3],
                   [1, 2, 3, 4]])

t1

ValueError: expected sequence of length 2 at dim 1 (got 3)

Error above suggest that in tensor, in every component within the same dimension you have to have same amount of elements.

In [ ]:

matrix1 = torch.tensor([[1, 2, 3],
                        [1, 2, 3],
                        [1, 2, 3]])

matrix1.ndim

In [ ]:
matrix1.shape

In [ ]:
mat = torch.tensor([[[1, 2],
                     [3, 4],
                     [5, 6]]])

mat.ndim

In [ ]:
mat.shape

In [ ]:
# END OF PRACTICE

### Random tensors
Why random tensors?

Random tensors are important, because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4) # torch.rand(size = (3, 4))
random_tensor

tensor([[0.0452, 0.5010, 0.6713, 0.3324],
        [0.3061, 0.6745, 0.2980, 0.4821],
        [0.2205, 0.7017, 0.6743, 0.7679]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour channel (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor.dtype # To check type of number in tensor

torch.float32

In [ ]:
random_zero_tensor = torch.zeros(size = (3, 4)) # Create tensor of all zeros
random_zero_tensor, random_zero_tensor.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]))

In [ ]:
random_one_tensor = torch.ones(size = (3, 4)) # Create tensor of all ones
random_one_tensor, random_one_tensor.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]))

In [ ]:
# We can also multiple/add/divide/subtract tensors
random_zero_tensor * random_one_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like

Torch arange -> https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
# Use torch.(a)range()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# If we want to create a tensor shape identical to one passed as argument,
# we use this method, which duplicates that tensor, and fiils it with zeros.
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Precision in computing, is a measure of detail in which the number is expressed.

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
  1. Tensors not right datatypes
  2. Tensors not right shape
  3. Tensors not on the right device

More -> https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, # Type of data/nums in tensor (None == torch.float32)
                                device = None, # What device tensor is on(None == CPU, there is CUDA for GPU, etc)
                                requires_grad = False) # If we want PyTorch to track gradient of tensor, more in future
float_32_tensor.dtype

torch.float32

32-bit means that number is stored in 32 bits. The more bits it is represented in, the number is more precisely represented, but slower to computer.

16-bit and lower are less precisely represented, but faster to compute.


In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

  1.Tensors not right datatypes - to get datatype from a tensor, use `tensor.dtype`

  2.Tensors not right shape - to get shape from a tensor, use `tensor.shape`

  3.Tensors not on the right device - to get device from a tensor, use `tensor.device`


In [ ]:
some_tensor = torch.rand(size = (3, 4))
some_tensor

tensor([[0.6777, 0.1217, 0.5704, 0.8531],
        [0.6689, 0.4958, 0.1921, 0.7181],
        [0.1670, 0.3555, 0.9586, 0.5113]])

In [ ]:
# Find out some detail about this tensor
print(some_tensor)
print("\n")
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device on which tensor is on: {some_tensor.device}")

tensor([[0.6777, 0.1217, 0.5704, 0.8531],
        [0.6689, 0.4958, 0.1921, 0.7181],
        [0.1670, 0.3555, 0.9586, 0.5113]])


Data type of tensor: torch.float32
Shape of tensor : torch.Size([3, 4])
Device on which tensor is on: cpu
