<a href="https://colab.research.google.com/github/Nenad523/mastering-git/blob/main/00PyTorchFundamentalsVideo(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Putting tensors and models on the GPU

The reason we want our tensors/models on GPU, because using GPU results in faster computations.

In [ ]:
import torch

# Create a tensor (default on the CPU)

tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU (Numpy only works on CPU)

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exercises and extra-curicullum

Link -> https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises